In [9]:
import pandas as pd
import numpy as np

In [10]:
train = pd.read_csv("./train_with_descriptors.csv")
test = pd.read_csv("./test_with_descriptors.csv")

In [11]:
# Dropping all null values
train = train.dropna()
# Replacing null values with mean based on techniques in titanic dataset 
test = test.fillna(test.mean())

In [23]:
train

,MaxEStateIndex,MinEStateIndex,MaxAbsEStateIndex,MinAbsEStateIndex,qed,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,NumRadicalElectrons,...,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea,Assay_ID,Expected
0,9.316200,-1.533785,9.316200,0.150485,0.794714,317.599,306.511,315.982463,100.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1644,2
1,10.532611,0.333788,10.532611,0.333788,0.516641,156.269,136.109,156.151415,66.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,2451,2
2,2.433032,0.000000,2.433032,0.000000,0.251327,362.086,313.702,361.347528,148.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,1384,2
3,10.355080,-0.613825,10.355080,0.282361,0.487998,255.665,245.585,255.052302,90.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16,2
5,12.034676,-2.419051,12.034676,0.546336,0.588579,242.346,223.194,242.056408,80.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1646,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75378,11.460021,-3.868472,11.460021,0.053611,0.712426,230.245,220.165,230.036128,82.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33,2
75379,5.928972,-2.841623,5.928972,0.082346,0.720533,313.747,296.611,313.041677,104.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1632,1
75380,4.975926,0.848333,4.975926,0.848333,0.596343,167.258,162.218,166.986341,50.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1373,1
75381,10.241948,0.324028,10.241948,0.324028,0.519485,128.215,112.087,128.120115,54.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,2
75382,12.552405,-0.188577,12.552405,0.048913,0.165457,636.962,572.450,636.486609,258.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,2,1

In [13]:
X = train.drop("Expected",axis=1)
y = train["Expected"]

# Using Decision Tree Classifier

In [17]:
from sklearn.tree import DecisionTreeClassifier

# Decision Tree Classifier
model = DecisionTreeClassifier()
model.fit(X,y)

DecisionTreeClassifier()

In [18]:
predict = model.predict(test)
predict

array([2, 2, 2, ..., 2, 2, 2])

In [19]:
print(np.count_nonzero(predict==1))
print(np.count_nonzero(predict==2))

1599
9395

In [20]:
# Create submission file 
submission_file = pd.read_csv("./sample_submission.csv")

In [21]:
submission_file

                                                      Id  Predicted
0                         CC1=CC(=C(C=C1)C(C)(C)C)O;1682          1
1      CCS(=O)(=O)C1=C(N=CC=C1)S(=O)(=O)NC(=O)NC2=NC(...          2
2      CC1=NC2=CC=CC=C2N1C3CC4CCC(C3)N4CCC5(CCN(CC5)C...          1
3                    CC1=CC(=O)[N-]S(=O)(=O)O1.[K+];1850          2
4      CCC(C)(C)C(=O)O[C@H]1C[C@H](C=C2[C@H]1[C@H]([C...          2
...                                                  ...        ...
10989  CC(=NOCC1=CC=CC=C1C(=NOC)C(=O)OC)C2=CC(=CC=C2)...          1
10990  C1=CC=C(C(=C1)C(C2=CC=C(C=C2)O)C3=CC=C(C=C3)O)...          2
10991  CC1=NC(=NC(=N1)OC)NC(=O)NS(=O)(=O)C2=CC=CC=C2C...          1
10992                           COP(=O)(OC)OC=C(Cl)Cl;28          2
10993                        C1=CC=C2C(=C1)C(=O)NS2;1855          2

[10994 rows x 2 columns]

In [22]:
submission_file["Predicted"] = predict
submission_file.to_csv("rdkit_submission_5.csv",index=False)